language: java
jdk:
  - openjdk11
branches:
  only:
    - master
before_install:
  - chmod +x gradlew
  - openssl aes-256-cbc -K $encrypted_e73d10d2bbb2_key -iv $encrypted_e73d10d2bbb2_iv
    -in prod.tar.enc -out prod.tar -d
  - tar xvf prod.tar
  - mkdir src/main/resources
  - mv application.yml src/main/resources/
  - mv application-local.yml src/main/resources/
  - mv application-real1.yml src/main/resources/
  - mv application-real2.yml src/main/resources/
  - mv application-prodDb.yml src/main/resources/
  - mv application-aws.yml src/main/resources/
  - mv application-security.yml src/main/resources/

cache:
  directories:
    - "$HOME/.m2/repository"
    - "$HOME/.gradle"
script: "./gradlew clean build"

before_deploy:
  #  - zip -r spring-deploy-docker * # (2)
  #  - mkdir -p deploy # (3)
  #  - mv spring-deploy-docker.zip deploy/spring-deploy-docker.zip
  - mkdir -p before-deploy
  - cp scripts/*.sh before-deploy/
  - cp appspec.yml before-deploy/
  - cp build/libs/*.jar before-deploy/
  - cd before-deploy && zip -r before-deploy *
  - cd ../ && mkdir -p deploy
  - mv before-deploy/before-deploy.zip deploy/dsu-reserve.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY         # Travis CI 에서 IAM 사용자 엑세스 키
    secret_access_key: $AWS_SECRET_KEY     # Travis CI 에서 IAM 사용자 비밀 엑세스 키
    bucket: dsu-reserve-build        # S3 Bucket 이름
    region: ap-northeast-2
    skip_cleanup: true
    acl: private               # zip 파일 공개 여부
    local_dir: deploy
    wait-until-deployed: true

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY # Travis repo setting에 설정된 값
    secret_access_key: $AWS_SECRET_KEY # Travis repo setting에 설정된 값

    bucket: dsu-reserve-build # S3 버킷
    key: dsu-reserve.zip # 빌드 파일을 압축해서 전달
    bundle_type: zip # 압축 확장자
    application: dsu-reserve # 웹 콘솔에서 등록한 CodeDeploy 애플리케이션

    deployment_group: dsu-reserve-group # 웹솔에서 등록한 CodeDeploy 배포 그룹

    region: ap-northeast-2
    wait-until-deployed: true

notifications:
  email:
    recipients:
      - heonga2@gmail.com
#dd:
#- openssl aes-256-cbc -K $encrypted_e73d10d2bbb2_key -iv $encrypted_e73d10d2bbb2_iv
#  -in prod.tar.enc -out prod.tar -d
